// <auto-generated />
using System;
using LifeRoutine.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeRoutine.Infra.Migrations
{
    [DbContext(typeof(LifeRoutineDbContext))]
    partial class LifeRoutineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("GrupoAlimentar")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("GrupoAlimentar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Nome");

                    b.Property<int>("RefeicaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RefeicaoId");

                    b.ToTable("Alimento", (string)null);
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.FichaAlimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("FichaAlimentacao", (string)null);
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.FichaCorporal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<float>("Altura")
                        .HasColumnType("FLOAT")
                        .HasColumnName("Altura");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("DataCriacao");

                    b.Property<Guid>("Guid")
                        .HasColumnType("BLOB")
                        .HasColumnName("Guid");

                    b.Property<float>("Peso")
                        .HasColumnType("FLOAT")
                        .HasColumnName("Peso");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("Usuario")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("FichaCorporal", (string)null);
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.FichaExercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("DataCriacao");

                    b.Property<Guid>("Guid")
                        .HasColumnType("BLOB")
                        .HasColumnName("Guid");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("Usuario")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("FichaExercicio", (string)null);
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Refeicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("DataDeCriacao");

                    b.Property<int?>("FichaAlimentacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FichaAlimentacaoId");

                    b.ToTable("Refeicao", (string)null);
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("DataNascimento");

                    b.Property<int?>("FichaAlimentacaoId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("FichaAlimentacaoId")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Alimento", b =>
                {
                    b.HasOne("LifeRoutine.Domain.Entities.Refeicao", null)
                        .WithMany("Alimentos")
                        .HasForeignKey("RefeicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Refeicao_Alimentos");
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.FichaCorporal", b =>
                {
                    b.HasOne("LifeRoutine.Domain.Entities.Usuario", "Usuario")
                        .WithMany("FichasCorporal")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FichasCorporal_Usuario");

                    b.OwnsOne("LifeRoutine.Domain.ValueObjects.Perimetria", "Perimetria", b1 =>
                        {
                            b1.Property<int>("FichaCorporalId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("Abdome")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Abdome");

                            b1.Property<float>("AnteBraço_Direito")
                                .HasColumnType("FLOAT")
                                .HasColumnName("AnteBraco_Direito");

                            b1.Property<float>("AnteBraço_Esquerdo")
                                .HasColumnType("FLOAT")
                                .HasColumnName("AnteBraco_Esquerdo");

                            b1.Property<float>("Braço_Direito")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Braco_Direito");

                            b1.Property<float>("Braço_Esquerdo")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Braco_Esquerdo");

                            b1.Property<float>("Cintura")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Cintura");

                            b1.Property<float>("Coxa_Direita")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Coxa_Direita");

                            b1.Property<float>("Coxa_Esquerda")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Coxa_Esquerda");

                            b1.Property<float>("Ombro")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Ombro");

                            b1.Property<float>("Panturrilha_Direita")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Panturrilha_Direita");

                            b1.Property<float>("Panturrilha_Esquerda")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Panturrilha_Esquerda");

                            b1.Property<float>("Quadril")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Quadril");

                            b1.Property<float>("Torax")
                                .HasColumnType("FLOAT")
                                .HasColumnName("Torax");

                            b1.HasKey("FichaCorporalId");

                            b1.ToTable("FichaCorporal");

                            b1.WithOwner()
                                .HasForeignKey("FichaCorporalId");
                        });

                    b.Navigation("Perimetria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.FichaExercicio", b =>
                {
                    b.HasOne("LifeRoutine.Domain.Entities.Usuario", "Usuario")
                        .WithMany("FichasExercicios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FichasExercicios_Usuario");

                    b.OwnsMany("LifeRoutine.Domain.ValueObjects.Exercicio", "Exercicios", b1 =>
                        {
                            b1.Property<int>("FichaExercicioId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DiasDaSemana")
                                .IsRequired()
                                .HasColumnType("SMALLINT")
                                .HasColumnName("Dias_Da_Semana");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Nome");

                            b1.Property<int>("Numero_De_Repeticoes")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("Numero_De_Repeticoes");

                            b1.Property<int>("Numero_De_Series")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("Numero_De_Series");

                            b1.HasKey("FichaExercicioId", "Id");

                            b1.ToTable("Exercicio");

                            b1.WithOwner()
                                .HasForeignKey("FichaExercicioId");
                        });

                    b.Navigation("Exercicios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Refeicao", b =>
                {
                    b.HasOne("LifeRoutine.Domain.Entities.FichaAlimentacao", null)
                        .WithMany("Refeicoes")
                        .HasForeignKey("FichaAlimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("LifeRoutine.Domain.Entities.FichaAlimentacao", "FichaAlimentacao")
                        .WithOne("Usuario")
                        .HasForeignKey("LifeRoutine.Domain.Entities.Usuario", "FichaAlimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FichaAlimentacao_Usuario");

                    b.OwnsOne("LifeRoutine.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("EnderecoDeEmail")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("NVARCHAR")
                                .HasColumnName("EnderecoDeEmail");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("LifeRoutine.Domain.ValueObjects.Senha", "Senha", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("SenhaHash")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("NVARCHAR")
                                .HasColumnName("SenhaHash");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FichaAlimentacao");

                    b.Navigation("Senha")
                        .IsRequired();
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.FichaAlimentacao", b =>
                {
                    b.Navigation("Refeicoes");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Refeicao", b =>
                {
                    b.Navigation("Alimentos");
                });

            modelBuilder.Entity("LifeRoutine.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("FichasCorporal");

                    b.Navigation("FichasExercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
